matrix:
    include:
      - language: node_js
        node_js:
          - "10"
        before_install:
            - chmod +x .travis/ci_node.sh  
        script: .travis/ci_node.sh
  
      - language: node_js
        node_js:
          - "8"
        before_install:
            - chmod +x .travis/ci_node.sh  
        script: .travis/ci_node.sh
  
      - os: osx
        language: objective-c
        osx_image: xcode9.4
        env:
          - JOB_NAME=IOS
        before_install:
             - chmod +x .travis/ci.sh  
        script: .travis/ci.sh
  
      - os: linux
        language: android
        jdk: openjdk8
        sudo: required
        android:
          components:
            - android-16
            - android-28
            - tools
            - platform-tools
            - build-tools-28.0.3
            - extra-google-m2repository
            - extra-android-m2repository
            - extra-google-google_play_services
        env:
          - JOB_NAME=ANDROID
        before_install:
            - chmod +x .travis/ci.sh 
        script: .travis/ci.sh